"""Tool implementations for the Agent Orchestrator."""
import json
import fitz  # PyMuPDF
from docx import Document
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
import logging
import re

from app.core.rag import rag_engine
from app.core.model_router import model_router
from app.core.config import settings

logger = logging.getLogger(__name__)

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================
# TOOL 1: Document Reader (PDF/DOCX text extraction)
# ============================================================
async def doc_reader(file_path: str) -> Dict[str, Any]:
    """Extract structured text from PDF/DOCX."""
    path = Path(file_path)
    if not path.exists():
        return {"error": f"File not found: {file_path}"}
    
    text = ""
    if path.suffix.lower() == ".pdf":
        doc = fitz.open(file_path)
        for i, page in enumerate(doc):
            text += f"\n[PAGE {i+1}] {page.get_text()}"
        doc.close()
    elif path.suffix.lower() in (".docx", ".doc"):
        from docx import Document as DocxDocument
        doc = DocxDocument(file_path)
        for i, para in enumerate(doc.paragraphs):
            text += f"\n{para.text}"
    else:
        return {"error": f"Unsupported format: {path.suffix}"}
    
    # Try to extract key-value pairs
    kv_pairs = {}
    for line in text.split("\n"):
        if ":" in line and len(line) < 200:
            parts = line.split(":", 1)
            key = parts[0].strip()
            val = parts[1].strip()
            if key and val:
                kv_pairs[key] = val
    
    return {
        "file_path": file_path,
        "full_text": text[:10000],  # truncate for LLM context
        "extracted_fields": kv_pairs,
        "page_count": max(1, len(text.split("[PAGE ")) - 1)
    }

# ============================================================
# TOOL 2: Knowledge Search (RAG)
# ============================================================
async def knowledge_search(query: str, machine_id: Optional[str] = None, top_k: int = 5) -> Dict[str, Any]:
    """Search local manuals for relevant specs/standards."""
    hits = rag_engine.search(query, machine_id, top_k)
    return {
        "query": query,
        "machine_id": machine_id,
        "results": hits,
        "count": len(hits)
    }

# ============================================================
# TOOL 3: Calculator - safe arithmetic
# ============================================================
async def calculator(expression: str) -> Dict[str, Any]:
    """Safely evaluate arithmetic expression."""
    allowed = set("0123456789.+-*/() ")
    clean_expr = expression.strip()
    if not all(c in allowed for c in clean_expr):
        return {"error": "Invalid characters in expression"}
    
    try:
        # Safe evaluation with empty builtins
        result = eval(clean_expr, {"__builtins__": {}}, {})
        return {"expression": clean_expr, "result": float(result)}
    except Exception as e:
        return {"error": f"Calculation failed: {str(e)}"}

# ============================================================
# TOOL 4: Report Generator - create DOCX
# ============================================================
async def report_generator(report_data: Dict[str, Any], template: str = "inspection_analysis") -> Dict[str, Any]:
    """Generate professional DOCX report from structured data."""
    doc = Document()
    
    # Base Style
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)
    
    # Title
    title = doc.add_heading('Inspection Analysis Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata table
    table = doc.add_table(rows=6, cols=2, style='Table Grid')
    meta = [
        ("Equipment", report_data.get("equipment", "N/A")),
        ("Analysis Date", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Report Type", report_data.get("analysis_type", "General")),
        ("Generated By", "Sovereign AI Workbench"),
        ("Confidence", f"{report_data.get('confidence', 0):.0%}"),
        ("Status", str(report_data.get("recommendation", "PENDING")).split(" - ")[0])
    ]
    for i, (k, v) in enumerate(meta):
        table.rows[i].cells[0].text = k
        table.rows[i].cells[1].text = str(v)
        table.rows[i].cells[0].paragraphs[0].runs[0].bold = True
    
    doc.add_paragraph()
    
    # Findings
    doc.add_heading('Findings', level=1)
    for finding in report_data.get("findings", []):
        doc.add_paragraph(str(finding), style='List Bullet')
    
    # Measurements
    if "measurements" in report_data and report_data["measurements"]:
        doc.add_heading('Measurements', level=1)
        m_table = doc.add_table(rows=1, cols=3, style='Table Grid')
        m_table.rows[0].cells[0].text = "Parameter"
        m_table.rows[0].cells[1].text = "Measured"
        m_table.rows[0].cells[2].text = "Required / Limit"
        for m in report_data["measurements"]:
            row = m_table.add_row()
            row.cells[0].text = str(m.get("parameter", ""))
            row.cells[1].text = str(m.get("measured", ""))
            row.cells[2].text = str(m.get("required", ""))
    
    # Deviations
    if "deviations" in report_data and report_data["deviations"]:
        doc.add_heading('Deviations', level=1)
        for d in report_data["deviations"]:
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(f"{d.get('parameter', 'Deviation')}: ").bold = True
            p.add_run(f"{d.get('deviation', '')} {d.get('unit', '')} ({d.get('status', '')})")
    
    # Recommendations
    doc.add_heading('Recommendations', level=1)
    for rec in report_data.get("recommendations", []):
        doc.add_paragraph(str(rec), style='List Bullet')
    
    # Sources / Citations
    if "citations" in report_data and report_data["citations"]:
        doc.add_heading('Sources', level=1)
        for cite in report_data["citations"]:
            doc.add_paragraph(f"[{cite.get('machine_id', 'MANUAL')}, Page {cite.get('source_page', 1)}] {str(cite.get('text_snippet', ''))[:150]}...", style='List Bullet')
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("CONFIDENTIAL - For Internal Use Only").italic = True
    
    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    equip = str(report_data.get("equipment", "UNKNOWN")).replace("/", "-")
    filename = f"Analysis_Report_{equip}_{timestamp}.docx"
    output_path = REPORTS_DIR / filename
    doc.save(output_path)
    
    return {
        "report_path": str(output_path),
        "filename": filename,
        "paragraphs": len(doc.paragraphs)
    }

# ============================================================
# TOOL REGISTRY
# ============================================================
TOOLS = {
    "doc_reader": {
        "fn": doc_reader,
        "description": "Extract text and structured fields from PDF/DOCX inspection reports",
        "params": {"file_path": "string"}
    },
    "knowledge_search": {
        "fn": knowledge_search,
        "description": "Search local manufacturing manuals for specs, standards, tolerances",
        "params": {"query": "string", "machine_id": "string?", "top_k": "int?"}
    },
    "calculator": {
        "fn": calculator,
        "description": "Perform safe arithmetic calculations (deviations, percentages, etc.)",
        "params": {"expression": "string"}
    },
    "report_generator": {
        "fn": report_generator,
        "description": "Generate professional DOCX report from structured analysis data",
        "params": {"report_data": "object", "template": "string?"}
    }
}
